version: '3.3'
services:
  app:
    build:
      context: '.'
    environment:
      - 'DB=assignment'
      - 'DB_User=assignment'
      - 'DB_Password=abc123'
    ports:
      #workaround for docker-compose bug: disable port binding
      - '8080'
    depends_on:
      - database
  database:
    image: 'postgres:9.6'
    environment:
      - 'POSTGRES_DB=assignment'
      - 'POSTGRES_USER=assignment'
      - 'POSTGRES_PASSWORD=abc123'
    volumes:
      - './database:/docker-entrypoint-initdb.d'
    ports:
      - '5432:5432/tcp'

volumes:
  database: {}